language: c
services:
  - docker
os: linux
dist: xenial
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
  - wget https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env
  - source xs-opam-ci.env
script: bash -ex ./.travis-docker.sh
env:
  global:
    - PINS="xenstore_transport:. xenstore-tool:."
  jobs:
    - PACKAGE="xenstore_transport"
    - PACKAGE="xenstore-tool"
